name: miEPG

on:
  schedule:
    - cron: '55 6 * * *'  # Ejecuta a las 6:55 AM cada día.
    - cron: '55 10 * * *' # Ejecuta a las 10:55 AM cada día.
    - cron: '55 14 * * *' # Ejecuta a las 2:55 PM cada día.
    - cron: '55 18 * * *' # Ejecuta a las 6:55 PM cada día.
  workflow_dispatch: # Permite ejecutar manualmente el flujo de trabajo.
permissions:
   contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Dar permisos de ejecución al script
      run: |
        chmod +x .github/workflows/EPG_script.sh
    - name: Ejecutar script
      run: .github/workflows/EPG_script.sh

    - name: Configurar identidad de Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
    - name: Hacer pull de los cambios remotos
      run: git pull origin main
        
    - name: Subir archivos 
      run: |
        git add .
        git commit -m "Nuevo miEPG.xml"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
